### PR TITLE
made everything ready for fdroid

### PR DESCRIPTION
**Pull request by theScrabi**
Hello,

it was awesome if your app was available on [fdroid](https://f-droid.org). You don't have to do much, I prepared everything so far. However Fdroid does not want libraries, due to security risks. Therefore I replaced the dx.jar with the actual source code.

I hope this is ok for you :)

rgds Schabi

### CODE REVIEW

**Comment by nikita36078** [comment]
Unfortunately, the last version of dx works incorrectly with emulator for some reason, so I'm going to add  old sources :)

**Comment by theScrabi** [comment]
All right thank you. Please let me know when you are done. I'll put it on fdroid then :)

**Comment by nikita36078** [comment]
Well, I'm done now, all dex.jar code is in dexlib module.

**Comment by nikita36078** [comment]
Ok, I fixed the build.

**Comment by theScrabi** [comment]
All right, just one thing, you may need to release a new version, than we are done :)

**Comment by nikita36078** [comment]
New version is ready

**Comment by theScrabi** [comment]
Thank you :D 

Merge request for adding this to fdroid is [out](https://gitlab.com/fdroid/fdroiddata/merge_requests/2934).
However there is a little issue on fdroid site. I hope the can resolve it.

**Pull request closed without merging**
