### PR TITLE
Symbian games

### PR DESCRIPTION
**Pull request by HeriKuen**
can you make j2meloader run a symbian game?

### CODE REVIEW

**Comment by nikita36078** [comment]
No, J2ME and Symbian is a completely different platforms, it's impossible. You need a Symbian emulator for that.

**Comment by HeriKuen** [comment]
Can you make a symbian emulator too ?

**Comment by nikita36078** [comment]
There's already one Symbian emulator in the development - [EKA2L1](https://github.com/EKA2L1/EKA2L1). Creating such an emulator is a very difficult task and can take years.

**Comment by yfaizin1** [comment]
how to make file rpkg and roms. example : 5320, 5530, 5800, c7, e5, n95, ngage

**Comment by nikita36078** [comment]
@yfaizin1 Ask it on [EKA2L1 Discord server](https://discord.gg/5Bm5SJ9), J2ME Loader has nothing to do it with it.

**Pull request closed without merging**
