### PR TITLE
QWERTY Keyboard feature

### PR DESCRIPTION
**Pull request by JoseskVolpe**
Fixed that dumb NullPointerExceptions that ocurred in some devices after openning the keyboard, additionaly, fixed some symbols that returned the wrong keycode to the input

### CODE REVIEW

**Comment by woesss** [comment]
The keyboard now opens, but not the first time. After the first time, the return key stops working until the very exit from the game, it only closes the keyboard when it is open.
Well, okay, I found my old attempt - it turned out not as bad as I thought. I will try to finalize it for the next release of JL-Mod.

**Comment by JoseskVolpe** [comment]
> 
> 
> The keyboard now opens, but not the first time. After the first time, the return key stops working until the very exit from the game, it only closes the keyboard when it is open.
> Well, okay, I found my old attempt - it turned out not as bad as I thought. I will try to finalize it for the next release of JL-Mod.

¿What's your phone, btw?

**Comment by JoseskVolpe** [comment]
Send the log please, i've made it throw some errors when it can't open, so your device is probably stucking in one of these errors on the first time

**Comment by JoseskVolpe** [comment]
Addedum: About the Back button glitch, i got it: it's not identifying the Back button as a command but as another character, i'm patching it

**Comment by JoseskVolpe** [comment]
Patched

--//--

Tested the application on Alcatel Pixi 4, keyboard seems to still send keycodes input to MIDlet after closing the MIDlet and opening another one. This bug seems to vary from device to device
The keyboard also worked at the first time on this device
Additionaly, the keyboard doesn't resize the application, that's another proprietary bug

Application seems fine on SM-T116BU and on K11 Plus, but with the "keyboard stopping sending input after closing MIDlet" issue

**Comment by JoseskVolpe** [comment]
Check if that works @woesss 
If it opens the keyboard at first time now

**Comment by woesss** [comment]
It also does not open for the first time. The problem is because of the focus - the view does not have time to receive it.  
I improved my version - I haven't noticed any serious problems yet:  
https://github.com/woesss/JL-Mod/pull/30

**Comment by JoseskVolpe** [comment]
@nikita36078 is going to merge @woesss's version, closing this Pull Request to avoid confusion

**Pull request closed without merging**
